apiVersion: apps/v1
kind: Deployment

metadata:
    name: webserver
spec:
    replicas: 2
    selector:
        matchLabels:
            app: server
    template:
        metadata:
             labels:
                  app: server 
        spec:
             containers:
                - name: webserver
                  image: josecyber/josecyber:latest
                  ports:
                  - containerPort: 80

            
          
